### ISSUE TITLE
Can't use application after authentication

### ISSUE THREAD

**Issue by seanerice** [alexwohlbruck/rack-finder#1]
After logging in with my OSM credentials, the application fails to respond to inputs. It requires a full clear of all site data to get it to respond again.

The console spits out an exception
```
index-32b2d040.js:2058 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'href')
    at Object.p (index-32b2d040.js:2058:284640)
    at update (index-32b2d040.js:4:2867)
    at flush (index-32b2d040.js:4:2248)
```

I believe this is happening because my OSM profile has no picture set. After setting a profile image, it works as expected.

This can be traced it back to src line 19 in `src/components/Profile.svelte`.

The line
```js
src={me?.img.href}
```

should be
```js
src={me?.img?.href}
```
in case the `me.img` is `null` or `undefined`

**Comment by seanerice** [comment]
I can confirm, this issue isn't replicable after setting a profile image in OSM. Immediately replicable after removing the image.

**Comment by alexwohlbruck** [comment]
lmao ahh its because you don't have a profile photo

**Comment by seanerice** [comment]
Gotta love it!
